### ISSUE TITLE
老哥注册不了啊

### ISSUE THREAD

**Issue by 466102196** [game-helper/hongbao2#14]
Internal Server Error

**Comment by zhuweiyou** [comment]
我们正在处理

**Comment by 466102196** [comment]
QQ邮箱也是挂的

**Comment by touzi** [comment]
估计用的是 QQ 的发件服务, 结果注册太多不给发送了.

**Comment by zhuweiyou** [comment]
已修复

**Comment by 466102196** [comment]
mac版   美团的Cookie 有方法么

**Comment by zhuweiyou** [comment]
@466102196 需要抓手机包，可以参考  https://github.com/game-helper/weixin 这个底部的几篇教程

**Comment by 466102196** [comment]
谢了 。。。 就是不想抓包才问问看的。。。还是得抓包

**Comment by touzi** [comment]
163 邮箱提示发送成功, 但没有收到邮件, 测试多个 163 邮箱都是如此.

**Comment by zhuweiyou** [comment]
昨天换了个发信账号，今天又被限制了。我们正在修 @touzi

**Comment by zhuweiyou** [comment]
@touzi 
应该可以了，请试一下

**Comment by touzi** [comment]
又可以注册了

**Comment by zhuweiyou** [comment]
嗯
