### ISSUE TITLE
老姐，小号是不是要弄个新手机号？

### ISSUE THREAD

**Issue by ipiao** [game-helper/hongbao2#15]

**Comment by zhuweiyou** [comment]
不是手机号，是微信号或者 QQ 号。跟手机号没任何关系哦

**Comment by touzi** [comment]
那我可以提供多个QQ号, 是不是抢到大红包的几率更大?

**Comment by zhuweiyou** [comment]
@touzi  大红包是必给，不是抢的。。

提供越多，是增加你领的次数。

**Comment by zhuweiyou** [comment]
已上线

**Comment by touzi** [comment]
没有手机号也能? 确定吗? , 我在仔细看看教程

**Comment by touzi** [comment]
嘻嘻已经测试过了, 不需要手机号, 那个教程写的有点问题. 其实只要打开抢红包连接就可以获取到 cookie

**Comment by zhuweiyou** [comment]
@touzi 请问哪个教程有问题，截图看下，我们优化一下说明
