### ISSUE TITLE
我大号怼上去了，这就很尴尬了

### ISSUE THREAD

**Issue by QinXZ1122** [game-helper/hongbao2#16]

**Comment by zhuweiyou** [comment]
会提供删除功能

**Comment by administratorc** [comment]
能不能增加一个  比如
（我今天领过大包了 红包链接（虽然可以留到第二天使用 但是存着要找）不用又浪费  就发上去供别人使用、别人领取的时候自动使用我的包）
而我有时候没有红包链接  则使用别人的

**Comment by zhuweiyou** [comment]
@administratorc 

这个功能暂时不是刚需，因为弄链接还是比较容易的。

如果发上去供别人使用，可能有人捣乱，乱填链接，而我们要验证这个链接是否有效，又要增加一些工作量，甚至可能需要消耗一个 cookie 次数去验证。

**Comment by administratorc** [comment]
@zhuweiyou 好的，感谢你的回复。

**Comment by QinXZ1122** [comment]
我现在领到大红包就自动给别人了   修改都修改不过来   怎么搞？

**Comment by zhuweiyou** [comment]
先修改号码，下次领就是你的。（当次不会变了）

**Comment by jitash** [comment]
什么时候出啊,大号一直被占着

**Comment by huangdenghe** [comment]
@jitash 红包领取功能和 Cookie 删除会同步上线，现在已经在内测中，我们并没有使用你的号做什么；如果急着删可以先发邮件给我 i@huangdenghe.com 内容包含你的注册的邮箱，并注明清空 Cookie

**Comment by zhuweiyou** [comment]
已上线
