### ISSUE TITLE
你好，作者。新版核心已完善

### ISSUE THREAD

**Issue by Sarkozy2018** [game-helper/hongbao2#20]
本团队已经实现新版饿了么抢大包核心，系统角色管理实现中，有联系方式私信交流一下么？
team:witker
email:Sarkozy@52sar.cn

**Comment by zhuweiyou** [comment]
不知道你指的核心是什么，原版的代码就可用的。

**Comment by Sarkozy2018** [comment]
新的是用Java后台写的，原版post会出现失败

**Comment by zhuweiyou** [comment]
之前的版本，某些逻辑确实没有处理到位，新版会做优化。

不过我们已经开发到一定程度了，现在再采用你们的方案，可能并不现实了。

**Comment by Sarkozy2018** [comment]
不是这个意思，我是说，互相交流，业务逻辑都是一样的，只是编程语言的实现过程不同罢了
