### ISSUE TITLE
上线了吗

### ISSUE THREAD

**Issue by cytmmm** [game-helper/hongbao2#22]

**Comment by zhuweiyou** [comment]
今天看看能不能上

**Comment by x113773** [comment]
要不先把删除上了吧，手机号又被改了。。

**Comment by zhuweiyou** [comment]
@x113773 删除不是单纯的 delete，还要考虑很多逻辑。

比如你贡献了、领取了，然后删了自己的 cookie 走人，是不允许的，会导致别人不够用。

如果着急的话，可以发邮箱到 i@huangdenghe.com ，内容包含你注册用的邮箱，并注明清空 Cookie，人工帮你删除。

**Comment by zhuweiyou** [comment]
已上线
