### ISSUE TITLE
消耗贡献次数计算错误

### ISSUE THREAD

**Issue by github4529** [game-helper/hongbao2#23]
![image](https://user-images.githubusercontent.com/19326244/37510812-61560454-2937-11e8-9ff7-ce08f9b95e1b.png)

![image](https://user-images.githubusercontent.com/19326244/37510832-7514e14a-2937-11e8-9c7e-0f1af864c17c.png)

4个cookie，次数20次，抢一个没人抢的第9个手气最佳，消耗次数10次（而不是9次）

**Comment by zhuweiyou** [comment]
你确定不是前面的领取消耗的 1 次吗。

请发一下你的邮箱，为了隐私不用完整，比如 xxxx****@xxx.com

**Comment by github4529** [comment]
452996***@qq.com

**Comment by github4529** [comment]
![image](https://user-images.githubusercontent.com/19326244/37511315-5a5b8dfc-2939-11e8-9768-347fd0aa026a.png)
可能是我获取cookie的时候填了一次手机消耗的次数？

**Comment by zhuweiyou** [comment]
应该不会。因为我们是读不到你的小号剩余几次的。直接按照 x5 减去消耗来计算的

**Comment by github4529** [comment]
我觉得可以查一下前面两次领取失败有没有消耗次数，因为次数不是实时更新的，刷新完才更新，我第三次操作后领到红包刷新发现剩余10次，与第9个手气最佳消耗次数不一致才觉得有问题

**Comment by zhuweiyou** [comment]
看第一张图，是不是你前面两次有消耗呀 ？

**Comment by github4529** [comment]
我自己查到了，第一个红包是领完的，所以不消耗次数；第二个红包手气最佳没了，但是消耗一次查看还剩余几个是手气最佳，消耗了一次；第三个消耗9次

**Comment by zhuweiyou** [comment]
对，是这样
