### ISSUE TITLE
不是已经有次数了吗，姿势错了吗

### ISSUE THREAD

**Issue by SSuperYe** [game-helper/hongbao2#25]
![ea007dacfe6c12df22b31232a2a4ecb](https://user-images.githubusercontent.com/20273427/37512676-c353acfa-293d-11e8-9e1b-dd04072fc239.png)，贡献了qq号

**Comment by huangdenghe** [comment]
请先阅读规则

**Comment by zhuweiyou** [comment]
看下第一条规则

**Comment by SSuperYe** [comment]
尴尬，懂了，是我没去看
