### ISSUE TITLE
美团领取最大红包有 bug

### ISSUE THREAD

**Issue by touzi** [game-helper/hongbao2#26]
我的美团红包链接第 8 个最大, 已经被领了两个, 提示最大红包已被领取, 但查看的时候只被领取了 4 个.

**Comment by huangdenghe** [comment]
@touzi 请发一下你的邮箱和红包链接，我们查一下

为了隐私邮箱不用完整，比如 xxxx****@xxx.com

**Comment by touzi** [comment]
https://activity.waimai.meituan.com/coupon/sharechannel/B2EA8E1ABA8B47EA82DB475BA17B517D?urlKey=6ECB18E932BE4F058DE37BAFDEB9FBB1&utm_term=AiphoneBgroupC9.0.0DweixinEwm-orderG4712B9D545604BB664FF38BDD51F3B144C313F8373AD2523629F5F69D5BFCC3120180316192854713&utm_source=appshare&utm_medium=iOSweb
好像是这个红包廉洁
邮箱: police***@163

**Comment by touzi** [comment]
我就成功了一个饿了吗, 其他的都是美团没成功的

**Comment by touzi** [comment]
bug 修复了, 我今天一次就成功抢到美团最大包了

**Comment by zhuweiyou** [comment]
可能还存在问题。100% 不敢说，但是也很多人领成功了
