### ISSUE TITLE
请问下领取红包不是要手机号吗

### ISSUE THREAD

**Issue by Ericzhou950729** [game-helper/hongbao2#27]
没有手机号不就是不能获得cookie吗？一般人都只有一个手机号绑定一个微信号，怎么才能贡献多的cookie

**Comment by zhuweiyou** [comment]
页面上写得很清楚，是贡献微信小号 cookie，与手机号无关。
目前贡献：美团微信号，饿了么 qq 号。

没规定一个手机只能注册一个微信呀？或者找朋友不点红包链接的微信号登一下，也可以

**Comment by C2unick** [comment]
贡献的qq号必须要在饿了么上面对应一个手机号吗？还是任何一个qq号都可以？

**Comment by zhuweiyou** [comment]
@C2unick  不用绑定手机号，

**Comment by Enck2015** [comment]
@zhuweiyou 手机号不都是和微信绑定的么，一个手机号只能注册一个微信的啊。
