### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by TravelEngineers** [game-helper/hongbao2#28]
现在都登陆不了哇

**Comment by TravelEngineers** [comment]
Provisional headers are shown
Accept:application/json, text/plain, */*
Content-Type:application/x-www-form-urlencoded
Origin:http://www.mtdhb.com
Referer:http://www.mtdhb.com/login/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by zhuweiyou** [comment]
你这边是哪个地区和网络？


我试了一下可以上去。

**Comment by TravelEngineers** [comment]
上海的长城宽带和上海电信都登陆不了哇。 @zhuweiyou

**Comment by zhuweiyou** [comment]
我这边是上海电信，可以登录额。。。

![image](https://user-images.githubusercontent.com/8413791/37554392-8e6de782-2a12-11e8-8a20-e26541d82861.png)

尝试运行一下

```bash
ping api.mtdhb.com
```

看看能不能 ping 通这个域名

**Comment by TravelEngineers** [comment]
ping不通哇 # @zhuweiyou

**Comment by TravelEngineers** [comment]
这边上google没问题

**Comment by zhuweiyou** [comment]
你的问题我记录了，后续会换个服务器。

临时方案，你开全局代理先试一下。

**Comment by zhuweiyou** [comment]
已修复
