### ISSUE TITLE
美团抓不到cookies

### ISSUE THREAD

**Issue by bbsxiaoxi** [game-helper/hongbao2#30]
美团抓不到cookies

**Comment by zhuweiyou** [comment]
你卡在教程哪一步了呢

**Comment by bbsxiaoxi** [comment]
就是按照教程来了，也抓到了网址了，但是就是没有显示cookies

**Comment by zhuweiyou** [comment]
能不能提供一下截图呢？你这样说，我们也不好帮你定位问题

**Comment by bbsxiaoxi** [comment]
![999999](https://user-images.githubusercontent.com/22465871/37551707-84fafbe0-29e0-11e8-88b4-1692e75c1e4d.JPG)

**Comment by huangdenghe** [comment]
@bbsxiaoxi 抓的接口不对，注意看教程截图，是个HTTPS协议的接口

**Comment by bbsxiaoxi** [comment]
我勾选了这呀
![121212121212](https://user-images.githubusercontent.com/22465871/37551738-44ced4a0-29e1-11e8-9022-90251d8a5b75.JPG)

**Comment by zhuweiyou** [comment]
现在结果如何？

**Comment by pzxton** [comment]
@bbsxiaoxi 检查下抓的接口可能不对  路径是下图
![image](https://user-images.githubusercontent.com/16535814/37817627-663b2fd2-2eb2-11e8-8bdb-5916f5d742e3.png)

**Comment by zhuweiyou** [comment]
现在有了提取工具，自行网页上查看使用方法
