### ISSUE TITLE
能否美团也用QQ小号

### ISSUE THREAD

**Issue by hshujun** [game-helper/hongbao2#34]
这样注册一个号美团饿了么各有5次机会了，而且微信小号不太好注册

**Comment by zhuweiyou** [comment]
这个限制不是我们做出的。

是美团红包页面，只能使用微信授权。

而饿了么既可以用 qq 又可以用微信，所以我们选择 qq。

**Comment by CPK1021** [comment]
明显是美团做出的。。。
