### ISSUE TITLE
忘记密码

### ISSUE THREAD

**Issue by lcxlcx1996** [game-helper/hongbao2#35]
如何找回密码？

**Comment by zhuweiyou** [comment]
**找回密码功能已在开发计划中**

如果你的号之前没有贡献过，就直接再注册一个吧

如果贡献过：
因为我们库里不存明文密码的，没办法直接告诉你明文密码是多少
到时候找回密码功能上线了，你再把原来号上贡献过的小号删除，转到新号上

**Comment by huangdenghe** [comment]
重置密码功能已上线
