### ISSUE TITLE
有次数情况下提示次数不足。并且未领取成功时次数被消耗

### ISSUE THREAD

**Issue by wolgy** [game-helper/hongbao2#36]
如图所示
![image](https://user-images.githubusercontent.com/30134245/37562678-622d2222-2aa9-11e8-97ac-c8a57b5d3361.png)

**Comment by zhuweiyou** [comment]
“请先仔细阅读规则再来领取，以免浪费次数”

看下规则第一条

**Comment by RPGLiker** [comment]
问一下贡献qq的cookie可以吗?微信号实在没那么多了

**Comment by zhuweiyou** [comment]
@RPGLiker  

选饿了么，可以贡献 QQ 的。

美团只能贡献微信，这是美团的限制，不是我们网站的限制。
