### ISSUE TITLE
贡献小号一直提示cookie

### ISSUE THREAD

**Issue by sorign** [game-helper/hongbao2#37]
今天贡献的时候一直提示cookie已存在？美团的饿了么没有试过

**Comment by huangdenghe** [comment]
@sorign PC 微信切换账号的时候，要退出并关闭应用，否则PC 微信的内置浏览器有缓存

**Comment by huangdenghe** [comment]
@sorign 要把微信关了，再打开

**Comment by sorign** [comment]
微信是指什么？手机微信还是啥？

**Comment by zhangximufeng** [comment]
饿了么，最好使用 无痕浏览 打开， 美团需要不同微信号

**Comment by sorign** [comment]
我大概知道原因了，我的账号被限制了 能帮忙解除一下吗，之前好像没有做验证 我用大号贡献了2个cookie

**Comment by sorign** [comment]
我大概知道原因了，我的账号被限制了 能帮忙解除一下吗，之前好像没有做验证 我用大号贡献了2个cookie

**Comment by sorign** [comment]
sun.morale@gmail.com  这个是账号

**Comment by zhuweiyou** [comment]
@sorign 早上解封过一拨人，目前没查到你被封
