### ISSUE TITLE
大红包被陌生号码领了，不是我输入的号码

### ISSUE THREAD

**Issue by zhangxianwen1993** [game-helper/hongbao2#38]
大红包被陌生号码领了，不是我输入的号码

**Comment by huangdenghe** [comment]
@zhangxianwen1993 以实际红包到账为准，请打开外卖应用查看

**Comment by zhuweiyou** [comment]
如果红包确实没到账，提供下页面顶部显示的 uid，我们查一下。

**Comment by zhangxianwen1993** [comment]
谢谢了，美团的大红包有到，不过显示列表那边不是显示我输入的账号，而且还是个陌生头像。饿了么的有显示出前三位电话号码，没有头像，红包也有到。

**Comment by zhuweiyou** [comment]
不能以页面显示为准，到了就行
