### ISSUE TITLE
服务器访问我们后台报400，缺少参数

### ISSUE THREAD

**Issue by zhangximufeng** [game-helper/hongbao2#40]
let cookie =  'userToken=B2022027D18A15ECC0F68899A2B66CCD40DCB6427289C549940CAD6590CAF97CF9D592E481554752C849CB6570003AF47FBCF71489532F4A23083A83D1A9E12F;JSESSIONID=963F6ACD0A0C01F748DB000A0ECD5CDD'

 request.post('http://api.mtdhb.com:8765/user/receiving')
        .set('Content-Type', 'application/json')
        .set('User-Agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36')
        .set('Host', 'api.mtdhb.com:8765')        
        .set('Origin', 'http://www.mtdhb.com')        
        .set('Referer', 'http://www.mtdhb.com/')
        .set('Cookie',cookie)     
        .send(data)
        .end((error,res)=>{
            console.log(res.body)
        })

**Comment by zhuweiyou** [comment]
GET 请求

**Comment by huangdenghe** [comment]
请求参数格式为 form-data，非 json

**Comment by zhangximufeng** [comment]
还真是。。get

**Comment by zhangximufeng** [comment]
掉用两次refresh 是为了什么？什么时候要发第二次refresh呢？
