### ISSUE TITLE
第一天贡献cookie,消耗了一次点击机会，被限制领取的问题

### ISSUE THREAD

**Issue by ng-show** [game-helper/hongbao2#42]
贡献cookie的当天，因为点击了一次链接查看cookie，导致次数少一次就被限制了，建议贡献cookie的当天初始化为次数为4

**Comment by zhuweiyou** [comment]
我们有容错的，允许抓 cookie 消耗一次。

**Comment by zhuweiyou** [comment]
现在应该解封了，你可以试试
