### ISSUE TITLE
领取一个10人的大红包，实际花费次数问题

### ISSUE THREAD

**Issue by blce** [game-helper/hongbao2#46]
比如一个10人的红包，已经被领了5个了，那我再用平台领取的话，是不是还是需要10次的可领取次数才可以领到红包？

**Comment by zhuweiyou** [comment]
按照实际使用扣次，10 - 5 = 5

**Comment by blce** [comment]
好的，谢谢大神们答疑解惑~~明天再试试看~

**Comment by blce** [comment]
@zhuweiyou 刚刚用领取功能领取了一个12人的包，已有一个被领，实际花费的使用次数还是12次哦，还有我让别人再打开看看，发现那个包还是未领取状态，但我的手机号已经实际到账了一个大红包，不知道是不是程序不一定是领自己提交的红包链接？我明天再试试看吧~

**Comment by zhuweiyou** [comment]
长久没有反馈，现将关闭，有问题再 reopen
