### ISSUE TITLE
饿了么

### ISSUE THREAD

**Issue by 15708451008** [game-helper/hongbao2#47]
饿了么登录QQ时，互联网回调地址校验加强，无法登陆

**Comment by 605666069** [comment]
+1，上午还能用

**Comment by zhuweiyou** [comment]
1、饿了么的某些配置过期了
2、饿了么故意关闭了 QQ 登录入口，全面走微信小程序了（新版分享出来是小程序，而且不能分享到 QQ 了）。

**Comment by 605666069** [comment]
还有什么途径可以贡献cookie

**Comment by zhuweiyou** [comment]
先过段时间看，如果确定是关闭了的话，饿了么也要贡献微信小号了。

**Comment by zhuweiyou** [comment]
饿了么增加了 “微信小号 cookie 贡献”，QQ 等以后能用了也可以继续用。

先 close 啦，有问题再开。

**Comment by johnnhan** [comment]
那之前贡献过的获得的次数会清零吗

**Comment by zhuweiyou** [comment]
@johnnhan  暂时还可以用

**Comment by zhuweiyou** [comment]
现饿了么已支持登录 QQ
