### ISSUE TITLE
根据教程来抓美团的cookie 不正确

### ISSUE THREAD

**Issue by mc7qing** [game-helper/hongbao2#48]
![image](https://user-images.githubusercontent.com/33148552/37751597-44a1976a-2dce-11e8-8037-e903b5ff3244.png)
抓到的cookie不正确

**Comment by mc7qing** [comment]
![image](https://user-images.githubusercontent.com/33148552/37752076-f9c56da4-2dd0-11e8-8ea8-404bf9f70502.png)
已解决 分享出来的连接改成http 拦截后查看发送的cookie即可

**Comment by zhuweiyou** [comment]
应该是你没打开 S 的选项

**Comment by mc7qing** [comment]
![image](https://user-images.githubusercontent.com/33148552/37752384-e5da8fd4-2dd2-11e8-9617-6fda004adfa3.png)
这个打开了 不知道怎么回事 https的不行
