### ISSUE TITLE
能否修改一下邮箱的打码策略

### ISSUE THREAD

**Issue by PlatypusPro** [game-helper/hongbao2#49]
RT
对于`@qq.com`和`@163.com`的打码策略没有意见
但是如果使用自己的域名邮箱，`@`之后的域名会完整显示出来 = =
希望判断一下域名部分然后打个码……多谢

**Comment by zhuweiyou** [comment]
谢谢反馈，我们会处理

**Comment by huangdenghe** [comment]
已修改
