### ISSUE TITLE
之前贡献cookie的时候页面没提示要用小号的cookie，把大号的贡献上去了，怎么删除？

### ISSUE THREAD

**Issue by x113773** [game-helper/hongbao2#5]
如题

**Comment by zhuweiyou** [comment]
抱歉，目前正在开发领取的功能，删除还没加上，我们后续会尽快更新这个功能。

现在还没领取功能，所以放心，你的号也不会被别人用来领取。

**Comment by x113773** [comment]
领取上线的时候，就能删除了吧，不然到时候就被别人用啦

**Comment by zhuweiyou** [comment]
@x113773  嗯 会加上的哈

**Comment by x113773** [comment]
嗯，好的，谢谢~。本人做JAVA开发的，如果有能帮忙的地方，可以联系我

**Comment by zhuweiyou** [comment]
好哦，我们的后台就是使用 java 开发的，后续开源了，欢迎来迭代和优化。

**Comment by x113773** [comment]
嗯，好啊

**Comment by x113773** [comment]
我发现我的微信号现在已经被用其他手机号绑定领取了，能不能给删一下数据库。。。。
coupon_uuid="6C151D5A7F63C9F54F0DE42724616FBDbZ%2BmLICtVRdtuxFppBfP

**Comment by zhuweiyou** [comment]
你为什么要用主号来领。。后面会开放删除功能。你现在直接再绑你的，就行了。

**Comment by x113773** [comment]
我是昨天贡献的，贡献的时候页面上没有提示要用小号（你们这个提示是后加的吧？），我已经改成我的了，后来发现又被改了

**Comment by x113773** [comment]
又变了，已经把我今天的次数用没了。。。

**Comment by zhuweiyou** [comment]
我们领取功能还没上线呢，怎么会把你的次数用完，你自己进页面就会领了的。

**Comment by x113773** [comment]
![_20180311161316](https://user-images.githubusercontent.com/24689696/37251241-4b21a6dc-2547-11e8-95ed-84db3c692741.jpg)
这个手机号也不是我的，改成我自己的过一会儿又变了，你是说也不是你们？

**Comment by zhuweiyou** [comment]
这里显示的应该是 **领取这个红包当时绑的号码**，你换了以后明天再领一个红包看看。

你提交的时候，确实会做号码绑定操作，用以验证 cookie 的有效性，然后存起来。

**Comment by x113773** [comment]
嗯，明天试试吧

**Comment by sunchenguang** [comment]
同把大号放上去了。。

**Comment by CPK1021** [comment]
老哥改java了吗 不是node开发的了吗

**Comment by zhuweiyou** [comment]
@CPK1021  

有人说 node 不能救中国，而 java 可以。

所以换语言写写。

**Comment by x113773** [comment]
有人 说的对！

**Comment by administratorc** [comment]
为什么这么厉害，老哥。

**Comment by zhuweiyou** [comment]
已上线
