### ISSUE TITLE
饿了么是不是出问题了

### ISSUE THREAD

**Issue by yionly1994** [game-helper/hongbao2#51]
qq登陆那个地方登录不上去，然后也能出来cookie，但是提交的时候就会显示cookie错误

**Comment by zhuweiyou** [comment]
页面上不是已经写了提示吗？现在饿了么暂时不能贡献，之前贡献的还可以用。

https://github.com/game-helper/hongbao2/issues/47

**Comment by zhuweiyou** [comment]
饿了么增加了 “微信小号 cookie 贡献”，QQ 等以后能用了也可以继续用。

先 close 啦，有问题再开。
