### ISSUE TITLE
应该是QQ的问题。不是饿了么的问题

### ISSUE THREAD

**Issue by Mathisdifficult** [game-helper/hongbao2#52]
http://wiki.connect.qq.com/%E4%BA%92%E8%81%94%E5%8A%A0%E5%BC%BA%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80%E6%A0%A1%E9%AA%8C%E9%80%9A%E7%9F%A5

**Comment by zhuweiyou** [comment]
QQ 更新了，饿了么没有跟着更新，不是饿了么的问题？

**Comment by Mathisdifficult** [comment]
理解的角度不一样吧

**Comment by zhuweiyou** [comment]
嗯。。。

**Comment by zhuweiyou** [comment]
饿了么增加了 “微信小号 cookie 贡献”，QQ 等以后能用了也可以继续用。

先 close 啦，有问题再开。
