### ISSUE TITLE
贡献cookie报错

### ISSUE THREAD

**Issue by git-shine** [game-helper/hongbao2#53]
Internal Server Error

**Comment by zhuweiyou** [comment]
应该是你复制的 COOKIE 不正确。
按照教程来，如果仍然报错，可以在教程底部扫码联系管理员。

**Comment by git-shine** [comment]
加了管理员还没有通过验证，通过了再说
我这边是拿一个未领取过的红包发的，再次点进去的时候红包已经被领取，且微信号被绑定了一个我不认识的美团账户，岂不是说明cookie已经被使用了？

**Comment by zhuweiyou** [comment]
会更换随机手机号绑定 去检测 这个 cookie 是否有效，但不会领取红包。

前提是提交的 cookie 是有效的。一旦提交上去了，就会投入使用。

如果没有提交上去，我们是不会入库的。

**Comment by git-shine** [comment]
不正确的cookie也能被成功绑定手机号嘛？

**Comment by zhuweiyou** [comment]
不正确怎么能绑对。

有可能是别的环节出问题了，比如你提交的是正确的，但是后续逻辑报错了，导致没有入库。

所以我说加管理员私聊一下比较快，可能他不在，耐心等通过吧。

**Comment by git-shine** [comment]
嗯，我这边提交的cookie已经被绑定了，但是没有入库，我私聊管理员好了
