### ISSUE TITLE
感觉领取次数不对啊

### ISSUE THREAD

**Issue by DougFlands** [game-helper/hongbao2#64]
比如8人包，领到6个，剩余次数1，按理来说可以领取的
剩余次数领第7个，然后自己号领第8个最大的。
但是网站提示不能了。。

**Comment by zhuweiyou** [comment]
请先看下规则第一条。

你自己大号那一次，也需要消耗一次 “大家贡献的小号”

你以为自己那一次，不用消耗？

**Comment by zhuweiyou** [comment]
目前逻辑：第一个红包会用小号去领，试一下列表返回几个，然后才决定用不用大号去领。

如果你只有 1 次，我们是认为你肯定领不到，因为第一次机会是要给小号领的。

**Comment by zhuweiyou** [comment]
现将关闭，有问题再 reopen
