### ISSUE TITLE
抓取qq上的cookie Chrome登陆红包的界面时候提示这个

### ISSUE THREAD

**Issue by kwongsw** [game-helper/hongbao2#65]
抓取cookie的时候出现这个
http://wiki.connect.qq.com/%E4%BA%92%E8%81%94%E5%8A%A0%E5%BC%BA%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E5%9B%9E%E8%B0%83%E5%9C%B0%E5%9D%80%E6%A0%A1%E9%AA%8C%E9%80%9A%E7%9F%A5
互联加强网站应用回调地址校验通知
这咋办？
还有，想问一下，这个红包qq和微信是分开来领的么？那还要手机号干嘛？

**Comment by zhuweiyou** [comment]
1、饿了么暂时不支持 QQ 登录了
2、贡献和领取是两码事，贡献是给我们 cookie，领取时候才填手机号

**Comment by cooljser** [comment]
现在可以用 QQ 抓取 cookie 了。
