### ISSUE TITLE
饿了么 问题反馈

### ISSUE THREAD

**Issue by kwongsw** [game-helper/hongbao2#66]
供献过一次微信饿了么的cookie，但是未使用过消耗次数，后来删掉了，
第二天领取红包时，领取的手机号被修改了。
这个是什么原因？

**Comment by huangdenghe** [comment]
1. 贡献的时候，就会改绑手机号，对 cookie 的有效性做校验。
2. 贡献的 cookie 可能在删除之前，已经被网站使用，并不是你自己未使用过消耗次数，就不会被用到；现在领红包是小号互点的方式。
