### ISSUE TITLE
貌似被墙。

### ISSUE THREAD

**Issue by Yangleis** [game-helper/hongbao2#69]
date：2018/4/3 18:25
我这上海电信的网络，服务器没响应。
爬墙后可使用。

**Comment by zhuweiyou** [comment]
我也是上海电信，可以打开
为了抗 D 现在套了一层 CF CDN，所以某些地区确实可能存在打不开的情况。

你可以换成阿里或者谷歌的 DNS 服务器，能够正常解析。
或者爬墙后，PING 一次，直接改 HOSTS 文件。
