### ISSUE TITLE
新注册的小号，按提示的步骤领红包复制cookie，提示已存在

### ISSUE THREAD

**Issue by x113773** [game-helper/hongbao2#8]
试了3个红包，都是这样，确定不是bug?

**Comment by zhuweiyou** [comment]
饿了么还是美团的？这个跟红包无关，只跟账号有关。

看日志和数据库，有验证通过的。

提供一下你提交的 cookie  开头部分？（防止暴露，不要全部），给我们查下。

**Comment by x113773** [comment]
美团的，
Cookie: coupon_uuid="86892638435B7A8594FA8E220562DF12a11yOt4FWzBKLoHqx3C08bz6CeAKHHceP9

**Comment by x113773** [comment]
账号178****2565

**Comment by zhuweiyou** [comment]
问题稍微晚一点回复你。

你先看这边列表，有没有展示贡献过的列表？

![image](https://user-images.githubusercontent.com/8413791/37250346-553124a2-2535-11e8-961c-e5c3600cecd3.png)

**Comment by x113773** [comment]
有，就是上一个问题说的，用大号贡献了一个。。。

**Comment by zhuweiyou** [comment]
你说的 “新注册的小号” 是什么号？这边的小号说的是微信、QQ 号，不是美团小号哦。

**Comment by x113773** [comment]
一个微信只能贡献一个啊？那我的小号是美团的。。。

**Comment by zhuweiyou** [comment]
这个是我们没写清楚，跟你的美团号是没有任何关系的

美团需要 “微信号”，饿了么需要 “QQ 号”

下次会优化一下描述文字

**Comment by x113773** [comment]
嗯，我换个微信试试

**Comment by x113773** [comment]
换了微信，还是不行，不会还限制设备吧。。
Cookie: webp=1; coupon_uuid="86892638435B7A8594FA8E220562DF12a11yOt4FWzBKLoHqx3C08bz6CeAKHHceP9XRuvqd0wvpX06h
