### ISSUE TITLE
7002 仅在微信端打开

### ISSUE THREAD

**Issue by xxxone** [game-helper/hongbao2#83]
user_agent是微信端  怎么还是报这个错呢

**Comment by zhuweiyou** [comment]
不能用网页版微信，要用客户端。

**Comment by xxxone** [comment]
那还得用open.weixin.qq.com授权登录之后 才进行提交吗？

**Comment by zhuweiyou** [comment]
要过授权的。

用微信桌面版 或者 手机版 都可以，网页版不行

**Comment by xxxone** [comment]
那cookie只要带ewxinfo就可以了？

**Comment by zhuweiyou** [comment]
不知道你想问什么，自己写领取功能？

**Comment by xxxone** [comment]
嗯算是 就是现在领取的时候 返回的log 出现了7002状态  但是号是授权过的

**Comment by zhuweiyou** [comment]
旧版的源码仅供参考，目前网站用的是修改过的。
你自己写的话，需要重新分析美团网站哦。

**Comment by xxxone** [comment]
OK

**Comment by iddddg** [comment]
想问下开发的咋样了?

**Comment by xxxone** [comment]
已经差不多了

**Comment by iddddg** [comment]
可否给个联系方式,有点疑惑,求教下
