### ISSUE TITLE
不知道为啥被限制了？

### ISSUE THREAD

**Issue by ElonXun** [game-helper/hongbao2#87]
由于您在其他地方使用了所贡献的 Cookie 次数，所以已被限制领取，请先阅读规则，愿意承诺遵守规则之后联系管理员解除限制！涉及以下小号：fmn

但这个小号没有再去用来点外卖。。。
账号是：894850427@qq.com
uuid: 3487

**Comment by zhuweiyou** [comment]
你是否在群里？找下群管理员解决。

**Comment by ElonXun** [comment]
@zhuweiyou 好的  谢谢
