### ISSUE TITLE
希望能做一个公众号让操作更方便

### ISSUE THREAD

**Issue by mrhuangbh** [game-helper/hongbao2#91]
比如可以在微信中将链接收藏直接发公众号里。自动领取。就像：绝对福利 这种公众号

**Comment by zhuweiyou** [comment]
你的想法很好，不过目前我们开发资源有限。
后期有可能会做，目前 API 端还没有完善好。

**Comment by mrhuangbh** [comment]
这个公众号好像跟你们的机制不太一样。可以不用贡献小号就领取饿了么红包。或许你们可以看看他是怎么弄的。还有另一个公众号：小小白犀牛

**Comment by zhuweiyou** [comment]
不用看了，市面上所有领红包的，都是抄我们的。不用贡献小号，只是他们自己内置了小号而已。

**Comment by mrhuangbh** [comment]
这样子呀😂😂😂好吧。

**Comment by mrhuangbh** [comment]
那现在有支付宝的口令红包链接。可以添加一个直接提交支付宝口令从而领红包的功能吗。口令如：[你有一个红包待领取] 邀请你来拼手气赢最高100元饿了么红包，复制本条信息打开支付宝即可参加。xN4Xye031z

**Comment by zhuweiyou** [comment]
不开发活动类型的红包领取功能，成本太高。活动完了就没用了

**Comment by mrhuangbh** [comment]
不对不对。我发错口令了。是这种：#吱口令#饿了么拼手气，第8个人领取的人得大红包（长按复制此消息，打开支付宝）S5IkLj505C。但是好像不能提取链接。

**Comment by zhuweiyou** [comment]
那个提不了。就算能抓包提，对普通用户成本过于高了。

**Comment by mrhuangbh** [comment]
👌好的谢谢

**Comment by xiongyizhu** [comment]
其实我怀疑那些公总号都是利用你这边的接口直接玩的，好几个公众号都是，比如吃货e福利。现在公众号都玩起收费模式了，一元钱抢一次。
